### ISSUE TITLE
Outdated TOS

### ISSUE THREAD

**Issue by PerryChalmers** [freeCodeCamp/terms-of-service#1]
All the the links on the TOS page still say freecodecamp.com. I have forked the terms-of-service and going through the files now to correct them. Just need confirmation that the email address changed as well?

**Comment by PerryChalmers** [comment]
56 instances. There is a comment near the bottom of the index that scripts should be moved down to the bottom. Do you want that done as well

**Comment by raisedadead** [comment]
Hi @PerryChalmers thanks for the issue, I am closing this, resolved by #2 
We look forward to more contributions from you in future.

Thanks and happy coding!
