### ISSUE TITLE
Is freeCodeCamp incorporated?

### ISSUE THREAD

**Issue by elaine-jackson** [freeCodeCamp/terms-of-service#4]
The terms of service refer to freeCodeCamp as "freeCodeCamp Inc" however is freeCodeCamp incorporated or are they a non-profit. This may lead to some confusion of those reading the terms of service.

**Comment by raisedadead** [comment]
Yes, freeCodeCamp Inc. is incorporated for some of the legal and financial aspects of operations. The company pays for salaries of the three employees of the org and the operational costs like servers, etc.

That said I am pinging @QuincyLarson for any specific queries that you may have or if you would like anything amended in the terms.

Feel free to continue on this thread.

**Comment by QuincyLarson** [comment]
@nsuchy Both. freeCodeCamp is incorporated as a nonprofit in the US.
